package com.project.po;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleid
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolecode
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolename
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleid
     *
     * @return the value of role.roleid
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleid
     *
     * @param roleid the value for role.roleid
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolecode
     *
     * @return the value of role.rolecode
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolecode
     *
     * @param rolecode the value for role.rolecode
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolename
     *
     * @return the value of role.rolename
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolename
     *
     * @param rolename the value for role.rolename
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
}