package com.project.po;

public class UserData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_data.id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_data.user_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_data.data
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_data.user_name
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_data.id
     *
     * @return the value of user_data.id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_data.id
     *
     * @param id the value for user_data.id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_data.user_id
     *
     * @return the value of user_data.user_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_data.user_id
     *
     * @param userId the value for user_data.user_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_data.data
     *
     * @return the value of user_data.data
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_data.data
     *
     * @param data the value for user_data.data
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_data.user_name
     *
     * @return the value of user_data.user_name
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_data.user_name
     *
     * @param userName the value for user_data.user_name
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}