package com.project.po;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.UserName
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PassWord
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regist_date
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private Date registDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Telephone
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Age
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Email
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.User_id
     *
     * @return the value of user.User_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.User_id
     *
     * @param userId the value for user.User_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.UserName
     *
     * @return the value of user.UserName
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.UserName
     *
     * @param username the value for user.UserName
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PassWord
     *
     * @return the value of user.PassWord
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PassWord
     *
     * @param password the value for user.PassWord
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regist_date
     *
     * @return the value of user.regist_date
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regist_date
     *
     * @param registDate the value for user.regist_date
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Telephone
     *
     * @return the value of user.Telephone
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Telephone
     *
     * @param telephone the value for user.Telephone
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Age
     *
     * @return the value of user.Age
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Age
     *
     * @param age the value for user.Age
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Email
     *
     * @return the value of user.Email
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Email
     *
     * @param email the value for user.Email
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_id
     *
     * @return the value of user.role_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_id
     *
     * @param roleId the value for user.role_id
     *
     * @mbggenerated Sat Jun 03 15:20:01 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

	public User(Integer userId, String username, String password,
			Date registDate, String telephone, Integer age, String email,
			Integer roleId) {
		super();
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.registDate = registDate;
		this.telephone = telephone;
		this.age = age;
		this.email = email;
		this.roleId = roleId;
	}
	
	public User(){
		
	}
    
}